name: Webclient CI

on:
  push:
    paths:
    - 'webclient/**.purs'
  pull_request:
    paths:
    - 'webclient/**.purs'

jobs:
  webclient:
    name: Webclient
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@v1

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('webclient/**/*.dhall') }}
          path: |
            webclient/.spago
            webclient/output

      - name: Setup Node.js environment
        uses: actions/setup-node@v1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('webclient/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install NPM dependencies
        run: npm ci
        working-directory: webclient

      - name: Build with spago
        run: spago build
        working-directory: webclient

      # TODO
      # - name: Test with spago
      #   run: spago test --no-install
      #   working-directory: core
      # - name: Deploy…
